#%RAML 0.8
title: API - FULLCONTROL - 2
version: 1.1-SNAPSHOT-DEV
baseUri: http://0.0.0.0:8081/api

/users:
  post:
    body:
      application/json:
        schema: !include api-create-user-in-schema.json
        example: !include api-create-user-in-example.json
    responses:
      201:
        body:
          application/json:
            schema: !include api-create-user-out-schema.json
            example: !include api-create-user-out-example.json
      400:
        body:
          application/json:
            example: |
              {
                "message":"Bad Request"
              }
